### ISSUE TITLE
Crash after adding stations and relaunching app

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/StreamRadio#32] opened 2020-08-29 14:57 UTC
Launch app
Add stations
Play/stop stations
Close app
Relaunch - crash
Deleting "Stations" folder in home/settings allows app to launch again

**Comment by humdingerb** [comment] 2020-08-30 07:18
I cannot reproduce this. Can you do a debug build and post the debugreport?

**Comment by jsteinaker** [comment] 2021-02-21 14:26
Can we close this? I've got a similar problem with *certain* stations, apparently it happened when the logo was too big. The version on HaikuDepot didn't crash so I went to check the last commits and the Load() method on the Station class got messed up in one of the cleanups/code styling changes. The PR I did fixes this (among other things) for me, so if someone can give it a try maybe we could close this ticket.

**Closed** 2023-12-02 14:57 UTC
